<div class="phone:ml-4">

  <table class="phone:w-[calc(100%-32px)] text-left border-b [&_th]:font-normal [&_th]:py-3 [&_td]:pl-2 [&_tr]:border-t [&_div]:border-r [&_div]:pr-2 bg-white">
    <tr>
      <th>
        <div>営業時間</div>
      </th>
      <td>10:00〜21:00</td>
    </tr>
    <tr>
      <th>
        <div>駐車場</div>
      </th>
      <td>5台</td>
    </tr>
    <tr>
      <th>
        <div>定休日</div>
      </th>
      <td>日曜日・祝日</td>
    </tr>
    <tr>
      <th>
        <div>住所</div>
      </th>
      <td>
        〒347-0009
        埼玉県加須市上三俣645ｰ1
      </td>
    </tr>
    <tr>
      <th>
        <div>アクセス</div>
      </th>
      <td>
        加須ICから車で3分
      </td>
    </tr>
  </table>
</div>